dataset:
    path: /content/syntax_finetuning/src/data/dataset_simple_rel/gsd/ru_simple_gsd_conll_short_test.json
    name: conll_short_gsd
    representation_type: conll_short
models:
  - original_model_id: Qwen/Qwen3-0.6B
    peft_model_id:
    is_instruct: True
    name: Qwen_0.6_Instruct
    model_library: vllm_part_regex
    max_tokens: 5000
output_dir: /content/pred_results

