dataset:
    train_file_path:
    dev_file_path: 
    test_file_path: /content/syntax_finetuning/src/data/dataset_simple_rel/gsd_grct_test/test_grct_test.json
    conll_test_file_path: None
    treebank: grct_syntagrus
    treebank_repr: grct
models:
  - original_model_id: RefalMachine/RuadaptQwen3-4B-Hybrid
    peft_model_id: Derinhelm/RuadaptQwen3_4B_Hybrid_syntagrus_grct
    is_instruct: True
    name: RuadaptQwen3_4B_Hybrid_syntagrus_grct
    model_library: vllm
    max_tokens: 5000
    index_finish: 30
root_output_dir_path: /content/pred_results
inference:
    seed:
        - 1000
        - 2000
    logit_parameters:
        - {}
        - name: main_logits
