dataset:
    path: /content/syntax_finetuning/src/data/dataset_simple_rel/gsd/ru_simple_gsd_grct_test.json
    name: grct_gsd
    representation_type: grct
models:
  - original_model_id: Qwen/Qwen3-0.6B
    peft_model_id: None # TODO
    is_instruct: True
    name: Qwen_0.6_Instruct
    model_library: vllm_outlines
output_dir: /content/pred_results

