dataset:
    path: syntagrus/grct_ru_syntagrus-test.json
    name: grct_syntagrus
    representation_type: grct
models:
  - original_model_id: Qwen/Qwen3-0.6B-Base
    peft_model_id: Derinhelm/Syntax_Qwen3_0_6B_Base_gsd_0_without_head
    is_instruct: False
    name: Qwen_0.6_Base
output_dir: .
