dataset:
    path: /syntax_finetuning/src/data/syntagrus/grct_ru_syntagrus-test.json
    name: grct_syntagrus
    representation_type: grct
models:
  - original_model_id: /models/RuadaptQwen3-4B-Hybrid
    peft_group:
      - /adapters/copied/Ruadapt4_Hybrid/RuadaptQwen3_4B_Hybrid_syntagrus_grct/0
      - /adapters/copied/Ruadapt4_Hybrid/RuadaptQwen3_4B_Hybrid_syntagrus_grct/1
    #peft_model_id: /adapters/copied/Ruadapt4_Hybrid/RuadaptQwen3_4B_Hybrid_syntagrus_grct/0
    is_instruct: True
    #name: Ruadapt4_Hybrid
output_dir: /pred_results
