formats:
  - grct
  - lct
  - conll
  - conll_short
simple_relations: True
treebanks:
  - input_directory: src/data/conllu/UD_Russian-GSD-master
    train:
      - ru_gsd-ud-train.conllu
    dev:
      - ru_gsd-ud-dev.conllu
    test:
      - ru_gsd-ud-test.conllu
    prefix: ru_simple_gsd
    output_directory: src/data/dataset_simple_rel/gsd
  - input_directory: src/data/conllu/UD_Russian-SynTagRus
    train:
      - ru_syntagrus-ud-train-a.conllu
      - ru_syntagrus-ud-train-b.conllu
      - ru_syntagrus-ud-train-c.conllu
    dev:
      - ru_syntagrus-ud-dev.conllu
    test:
      - ru_syntagrus-ud-test.conllu
    prefix: ru_simple_syntagrus
    output_directory: src/data/dataset_simple_rel/syntagrus
  - input_directory: src/data/conllu/UD_Russian-Taiga
    train:
      - ru_taiga-ud-train-a.conllu
      - ru_taiga-ud-train-b.conllu
      - ru_taiga-ud-train-c.conllu
      - ru_taiga-ud-train-d.conllu
      - ru_taiga-ud-train-e.conllu
    dev:
      - ru_taiga-ud-dev.conllu
    test:
      - ru_taiga-ud-test.conllu
    prefix: ru_simple_taiga
    output_directory: src/data/dataset_simple_rel/taiga
