formats:
  - grct
  - lct
  - conll
simple_relations: False
treebanks:
  - input_directory: src/data/conllu/UD_Russian-GSD-master
    train:
      - ru_gsd-ud-train.conllu
    dev:
      - ru_gsd-ud-dev.conllu
    test:
      - ru_gsd-ud-test.conllu
    prefix: ru_full_gsd
    output_directory: src/data/dataset_full_rel/gsd
  - input_directory: src/data/conllu/UD_Russian-SynTagRus
    train:
      - ru_syntagrus-ud-train-a.conllu
      - ru_syntagrus-ud-train-b.conllu
      - ru_syntagrus-ud-train-c.conllu
    dev:
      - ru_syntagrus-ud-dev.conllu
    test:
      - ru_syntagrus-ud-test.conllu
    prefix: ru_full_syntagrus
    output_directory: src/data/dataset_full_rel/syntagrus
