dataset_config:
  train_file_path: /content/syntax_finetuning_data/dataset_simple_rel/UD_Russian-SynTagRus/ru_simple_syntagrus_grct_train.json
  dev_file_path: /content/syntax_finetuning_data/dataset_simple_rel/UD_Russian-SynTagRus/ru_simple_syntagrus_grct_dev.json
  test_file_path: /content/syntax_finetuning_data/dataset_simple_rel/UD_Russian-SynTagRus/ru_simple_syntagrus_grct_test.json
  conll_test_file_path: /content/syntax_finetuning_data/conllu/UD_Russian-SynTagRus/ru_syntagrus-ud-test.conllu
  # conll_test_file_path is used for metric evaluation 
  treebank_repr: grct
  treebank: syntagrus_grct
inference_models:
  - original_model_id: Qwen/Qwen3-0.6B
    peft_model_id: /content/syntax_adapters/Qwen3_0_6B_ru_syntagrus_grct
    is_instruct: True
    name: Qwen3_0_6B_ru_syntagrus_grct
    model_library: vllm
    max_tokens: 5000
root_output_dir_path: /content/results
inference:
    seed:
        - 42
    logit_parameters:
        - name: main_logits
    model_parameters:
        - model_name: Qwen3_0_6B_ru_syntagrus_grct
    treebank_parameters:
        - treebank_name: syntagrus_grct
