dataset_config:
 - train_file_path: /content/syntax_finetuning/src/data/dataset_simple_rel/syntagrus/ru_simple_syntagrus_grct_train.json
   dev_file_path: /content/syntax_finetuning/src/data/dataset_simple_rel/syntagrus/ru_simple_syntagrus_grct_dev.json
   test_file_path: /content/syntax_finetuning/src/data/dataset_simple_rel/syntagrus/ru_simple_syntagrus_grct_test.json
   conll_test_file_path: /content/syntax_finetuning/src/data/conllu/UD_Russian-SynTagRus/ru_syntagrus-ud-test-1479-6402-6489.conllu
   # conll_test_file_path is used for metric evaluation 
   treebank_repr: grct
   treebank: syntagrus_grct_hard
   # syntagrus_grct_1479_metric_less_ruadapt4
   # syntagrus_grct_6402_text_after_bracket_qwen4
   # syntagrus_grct_6489_wrong_grct_ruadapt4
inference_models:
  - original_model_id: RefalMachine/RuadaptQwen3-4B-Hybrid
    peft_model_id: Derinhelm/RuadaptQwen3_4B_Hybrid_syntagrus_grct
    is_instruct: True
    name: Ruadapt4
    model_library: vllm
    max_tokens: 5000
  - original_model_id: Qwen/Qwen3-4B
    peft_model_id: Derinhelm/Qwen3_4B_syntagrus_grct
    is_instruct: True
    name: Qwen4
    model_library: vllm
    max_tokens: 5000
root_output_dir_path: /content/results/hard_cases
inference:
    seed:
        - 42
    logit_parameters:
        - {}
        - name: original_logits
        - name: main_logits
    model_parameters:
        - model_name: Ruadapt4
        - model_name: Qwen4
    treebank_parameters:
        - treebank_name: syntagrus_grct_hard
          index_set: [ 1479, 6402, 6489]
