dataset_config:
  train_file_path: /content/syntax_finetuning/src/data/dataset_simple_rel/gsd_grct_test/test_grct_train.json
  dev_file_path: /content/syntax_finetuning/src/data/dataset_simple_rel/gsd_grct_test/test_grct_dev.json
  test_file_path: /content/syntax_finetuning/src/data/dataset_simple_rel/gsd_grct_test/test_grct_test.json
  conll_test_file_path: /content/syntax_finetuning/src/data/dataset_simple_rel/gsd_grct_test/test_conll_test.conllu
  # conll_test_file_path is used for metric evaluation 
  treebank_repr: grct
  treebank: grct_syntagrus
inference_models:
  - original_model_id: Previous # TODO: заменить Previous и True по умолчанию
    peft_model_id: Previous
    is_instruct: True
    name: Previous
    model_library: vllm
    max_tokens: 5000
root_output_dir_path: /content/results
inference:
    seed:
        - 1000
        - 2000
    logit_parameters:
        - {}
        - name: main_logits
    model_parameters:
        - model_name: Previous
    treebank_parameters:
        - treebank_name: grct_syntagrus
          index_finish: 30
