dataset_config:
  train_file_path: /content/syntax_finetuning/src/data/gsd/conll_ru_gsd-train.json
  dev_file_path: /content/syntax_finetuning/src/data/gsd/conll_ru_gsd-dev.json
model_config:
  model_name: Qwen/Qwen3-0.6B-Base
  is_instruct: False
root_output_dir_path: /content/syntax_finetuning/results
epochs: 1
batch_size: 16

